Programming Focused:

In [153]:
import pandas as pd
import numpy as np
from datetime import datetime

In [154]:
df1=pd.read_csv('df1.csv',parse_dates=['eventTimestamp'])
df1.drop_duplicates(inplace=True)
df1['eventTimestamp']=df1['eventTimestamp'].str.slice(0,10)
df1['eventTimestamp']=pd.to_datetime(df1['eventTimestamp'],format='mixed')

• For every day and every platform: The total of unique users connected on that day. Name this column “DAU”.

In [155]:
df1=df1[df1['eventName']=='gameStarted']
Data=df1.groupby(['platform','eventName','eventTimestamp'])['userID'].nunique().reset_index()
Data=Data.rename(columns={'userID': 'DAU'})
Data

    platform    eventName eventTimestamp  DAU
0        IOS  gameStarted     2017-03-06  638
1        IOS  gameStarted     2017-04-06  658
2        IOS  gameStarted     2017-05-06  636
3        IOS  gameStarted     2017-06-06  580
4        IOS  gameStarted     2017-06-13  549
5        IOS  gameStarted     2017-06-14  574
6        IOS  gameStarted     2017-06-15  575
7        IOS  gameStarted     2017-06-16  564
8        IOS  gameStarted     2017-06-17  596
9        IOS  gameStarted     2017-06-18  594
10       IOS  gameStarted     2017-06-19  551
11       IOS  gameStarted     2017-06-20  537
12       IOS  gameStarted     2017-06-21  439
13       IOS  gameStarted     2017-06-22  423
14       IOS  gameStarted     2017-06-23  379
15       IOS  gameStarted     2017-06-24  375
16       IOS  gameStarted     2017-06-25  357
17       IOS  gameStarted     2017-06-26  340
18       IOS  gameStarted     2017-06-27  340
19       IOS  gameStarted     2017-06-28  341
20       IOS  gameStarted     2017-06-29  291
21       IOS  gameStarted     2017-06-30  262
22       IOS  gameStarted     2017-07-06  691
23       IOS  gameStarted     2017-08-06  759
24       IOS  gameStarted     2017-09-06  631
25       IOS  gameStarted     2017-10-06  621
26       IOS  gameStarted     2017-11-06  639
27       IOS  gameStarted     2017-12-06  621
28  STEAM_PC  gameStarted     2017-03-06  327
29  STEAM_PC  gameStarted     2017-04-06  334
30  STEAM_PC  gameStarted     2017-05-06  289
31  STEAM_PC  gameStarted     2017-06-06  272
32  STEAM_PC  gameStarted     2017-06-13  426
33  STEAM_PC  gameStarted     2017-06-14  368
34  STEAM_PC  gameStarted     2017-06-15  376
35  STEAM_PC  gameStarted     2017-06-16  386
36  STEAM_PC  gameStarted     2017-06-17  395
37  STEAM_PC  gameStarted     2017-06-18  418
38  STEAM_PC  gameStarted     2017-06-19  326
39  STEAM_PC  gameStarted     2017-06-20  256
40  STEAM_PC  gameStarted     2017-06-21  211
41  STEAM_PC  gameStarted     2017-06-22  198
42  STEAM_PC  gameStarted     2017-06-23  183
43  STEAM_PC  gameStarted     2017-06-24  181
44  STEAM_PC  gameStarted     2017-06-25  164
45  STEAM_PC  gameStarted     2017-06-26  163
46  STEAM_PC  gameStarted     2017-06-27  142
47  STEAM_PC  gameStarted     2017-06-28  139
48  STEAM_PC  gameStarted     2017-06-29  134
49  STEAM_PC  gameStarted     2017-06-30  125
50  STEAM_PC  gameStarted     2017-07-06  228
51  STEAM_PC  gameStarted     2017-08-06  198
52  STEAM_PC  gameStarted     2017-09-06  205
53  STEAM_PC  gameStarted     2017-10-06  229
54  STEAM_PC  gameStarted     2017-11-06  414
55  STEAM_PC  gameStarted     2017-12-06  465

• The total of new unique users who entered the app on that day. Name this column “New Players”.

In [156]:
df1=df1[df1['eventName']=='gameStarted']
df1=df1[df1['eventTimestamp']==df1['gaUserStartDate']]
df1[['eventTimestamp','eventName','userID']]
new_unique=df1.groupby(['platform','eventName','eventTimestamp'])['userID'].nunique().reset_index()
new_unique=new_unique.rename(columns={'userID': 'New Players'})
new_unique.sort_values(by='New Players', ascending=False)

    platform    eventName eventTimestamp  New Players
35  STEAM_PC  gameStarted     2017-12-06          297
13       IOS  gameStarted     2017-08-06          245
34  STEAM_PC  gameStarted     2017-11-06          243
12       IOS  gameStarted     2017-07-06          222
22  STEAM_PC  gameStarted     2017-06-13          208
0        IOS  gameStarted     2017-03-06          182
18  STEAM_PC  gameStarted     2017-03-06          182
14       IOS  gameStarted     2017-09-06          180
1        IOS  gameStarted     2017-04-06          179
2        IOS  gameStarted     2017-05-06          177
27  STEAM_PC  gameStarted     2017-06-18          169
19  STEAM_PC  gameStarted     2017-04-06          165
24  STEAM_PC  gameStarted     2017-06-15          163
26  STEAM_PC  gameStarted     2017-06-17          156
15       IOS  gameStarted     2017-10-06          154
3        IOS  gameStarted     2017-06-06          151
16       IOS  gameStarted     2017-11-06          147
25  STEAM_PC  gameStarted     2017-06-16          145
23  STEAM_PC  gameStarted     2017-06-14          143
17       IOS  gameStarted     2017-12-06          138
8        IOS  gameStarted     2017-06-17          136
9        IOS  gameStarted     2017-06-18          129
7        IOS  gameStarted     2017-06-16          126
5        IOS  gameStarted     2017-06-14          121
20  STEAM_PC  gameStarted     2017-05-06          118
21  STEAM_PC  gameStarted     2017-06-06          110
10       IOS  gameStarted     2017-06-19          110
4        IOS  gameStarted     2017-06-13          106
11       IOS  gameStarted     2017-06-20          102
28  STEAM_PC  gameStarted     2017-06-19          101
6        IOS  gameStarted     2017-06-15          101
33  STEAM_PC  gameStarted     2017-10-06           78
30  STEAM_PC  gameStarted     2017-07-06           63
31  STEAM_PC  gameStarted     2017-08-06           62
29  STEAM_PC  gameStarted     2017-06-20           53
32  STEAM_PC  gameStarted     2017-09-06           49

• The raw total of sessions (a session is when the game is started). Name this column “Sessions”.

In [157]:
sess=df1[df1['eventName']=='gameStarted']
sess=df1.groupby(['eventTimestamp','platform'])['userID'].count().reset_index()
sess=sess.rename(columns={'eventName': 'Sessions'})
sess

   eventTimestamp  platform  userID
0      2017-03-06       IOS     304
1      2017-03-06  STEAM_PC     266
2      2017-04-06       IOS     303
3      2017-04-06  STEAM_PC     226
4      2017-05-06       IOS     334
5      2017-05-06  STEAM_PC     171
6      2017-06-06       IOS     210
7      2017-06-06  STEAM_PC     136
8      2017-06-13       IOS     198
9      2017-06-13  STEAM_PC     305
10     2017-06-14       IOS     211
11     2017-06-14  STEAM_PC     186
12     2017-06-15       IOS     146
13     2017-06-15  STEAM_PC     197
14     2017-06-16       IOS     199
15     2017-06-16  STEAM_PC     211
16     2017-06-17       IOS     219
17     2017-06-17  STEAM_PC     245
18     2017-06-18       IOS     208
19     2017-06-18  STEAM_PC     240
20     2017-06-19       IOS     170
21     2017-06-19  STEAM_PC     130
22     2017-06-20       IOS     196
23     2017-06-20  STEAM_PC      66
24     2017-07-06       IOS     349
25     2017-07-06  STEAM_PC      90
26     2017-08-06       IOS     422
27     2017-08-06  STEAM_PC      95
28     2017-09-06       IOS     261
29     2017-09-06  STEAM_PC      78
30     2017-10-06       IOS     277
31     2017-10-06  STEAM_PC     122
32     2017-11-06       IOS     242
33     2017-11-06  STEAM_PC     339
34     2017-12-06       IOS     206
35     2017-12-06  STEAM_PC     405

• The raw total of matches started. Name this column “Matches”.

In [158]:
df1=pd.read_csv('df1.csv',parse_dates=['eventTimestamp'])
df1.drop_duplicates(inplace=True)
df1['eventTimestamp']=df1['eventTimestamp'].str.slice(0,10)
df1['eventTimestamp']=pd.to_datetime(df1['eventTimestamp'],format='mixed')
df1=df1[df1['eventName']=='matchStarted']
Matches=df1.groupby(['eventTimestamp','platform'])['userID'].size().reset_index(name='Matches')
Matches

   eventTimestamp  platform  Matches
0      2017-03-06       IOS     5197
1      2017-03-06  STEAM_PC     3071
2      2017-04-06       IOS     5946
3      2017-04-06  STEAM_PC     3109
4      2017-05-06       IOS     5286
5      2017-05-06  STEAM_PC     2526
6      2017-06-06       IOS     4542
7      2017-06-06  STEAM_PC     2313
8      2017-06-13       IOS     4076
9      2017-06-13  STEAM_PC     3444
10     2017-06-14       IOS     4123
11     2017-06-14  STEAM_PC     2836
12     2017-06-15       IOS     4501
13     2017-06-15  STEAM_PC     2647
14     2017-06-16       IOS     4483
15     2017-06-16  STEAM_PC     2972
16     2017-06-17       IOS     5161
17     2017-06-17  STEAM_PC     3513
18     2017-06-18       IOS     4749
19     2017-06-18  STEAM_PC     3685
20     2017-06-19       IOS     4231
21     2017-06-19  STEAM_PC     2451
22     2017-06-20       IOS     3785
23     2017-06-20  STEAM_PC     1886
24     2017-06-21       IOS     3400
25     2017-06-21  STEAM_PC     1482
26     2017-06-22       IOS     3512
27     2017-06-22  STEAM_PC     1383
28     2017-06-23       IOS     3131
29     2017-06-23  STEAM_PC     1223
30     2017-06-24       IOS     3182
31     2017-06-24  STEAM_PC     1279
32     2017-06-25       IOS     3142
33     2017-06-25  STEAM_PC     1145
34     2017-06-26       IOS     2675
35     2017-06-26  STEAM_PC      894
36     2017-06-27       IOS     2414
37     2017-06-27  STEAM_PC      893
38     2017-06-28       IOS     3220
39     2017-06-28  STEAM_PC     1629
40     2017-06-29       IOS     3705
41     2017-06-29  STEAM_PC     1363
42     2017-06-30       IOS     2978
43     2017-06-30  STEAM_PC     1041
44     2017-07-06       IOS     5022
45     2017-07-06  STEAM_PC     1809
46     2017-08-06       IOS     5516
47     2017-08-06  STEAM_PC     1899
48     2017-09-06       IOS     4470
49     2017-09-06  STEAM_PC     1961
50     2017-10-06       IOS     5358
51     2017-10-06  STEAM_PC     2275
52     2017-11-06       IOS     5603
53     2017-11-06  STEAM_PC     3510
54     2017-12-06       IOS     4568
55     2017-12-06  STEAM_PC     4173

• The raw total of matches lost. Name this column “Losses”.

In [159]:
df1=pd.read_csv('df1.csv',parse_dates=['eventTimestamp'])
df1.drop_duplicates(inplace=True)
df1['eventTimestamp']=df1['eventTimestamp'].str.slice(0,10)
df1['eventTimestamp']=pd.to_datetime(df1['eventTimestamp'],format='mixed')
df1=df1[df1['matchResult']=='Loss']
Losses=df1.groupby(['eventTimestamp','platform'])['userID'].size().reset_index(name='Losses')
Losses

   eventTimestamp  platform  Losses
0      2017-03-06       IOS    1942
1      2017-03-06  STEAM_PC    1062
2      2017-04-06       IOS    2301
3      2017-04-06  STEAM_PC    1062
4      2017-05-06       IOS    1938
5      2017-05-06  STEAM_PC     934
6      2017-06-06       IOS    1674
7      2017-06-06  STEAM_PC     885
8      2017-06-13       IOS    1542
9      2017-06-13  STEAM_PC    1086
10     2017-06-14       IOS    1515
11     2017-06-14  STEAM_PC     960
12     2017-06-15       IOS    1727
13     2017-06-15  STEAM_PC     834
14     2017-06-16       IOS    1787
15     2017-06-16  STEAM_PC     892
16     2017-06-17       IOS    2074
17     2017-06-17  STEAM_PC    1186
18     2017-06-18       IOS    1870
19     2017-06-18  STEAM_PC    1222
20     2017-06-19       IOS    1666
21     2017-06-19  STEAM_PC     852
22     2017-06-20       IOS    1458
23     2017-06-20  STEAM_PC     768
24     2017-06-21       IOS    1512
25     2017-06-21  STEAM_PC     658
26     2017-06-22       IOS    1550
27     2017-06-22  STEAM_PC     616
28     2017-06-23       IOS    1329
29     2017-06-23  STEAM_PC     520
30     2017-06-24       IOS    1381
31     2017-06-24  STEAM_PC     604
32     2017-06-25       IOS    1431
33     2017-06-25  STEAM_PC     524
34     2017-06-26       IOS    1124
35     2017-06-26  STEAM_PC     450
36     2017-06-27       IOS     998
37     2017-06-27  STEAM_PC     443
38     2017-06-28       IOS    1476
39     2017-06-28  STEAM_PC     769
40     2017-06-29       IOS    1597
41     2017-06-29  STEAM_PC     647
42     2017-06-30       IOS    1304
43     2017-06-30  STEAM_PC     475
44     2017-07-06       IOS    1730
45     2017-07-06  STEAM_PC     729
46     2017-08-06       IOS    1805
47     2017-08-06  STEAM_PC     791
48     2017-09-06       IOS    1570
49     2017-09-06  STEAM_PC     801
50     2017-10-06       IOS    1977
51     2017-10-06  STEAM_PC     993
52     2017-11-06       IOS    2208
53     2017-11-06  STEAM_PC    1227
54     2017-12-06       IOS    1699
55     2017-12-06  STEAM_PC    1416

• The raw total of matches won. Name this column “Wins”.

In [160]:
df1=pd.read_csv('df1.csv',parse_dates=['eventTimestamp'])
df1.drop_duplicates(inplace=True)
df1['eventTimestamp']=df1['eventTimestamp'].str.slice(0,10)
df1['eventTimestamp']=pd.to_datetime(df1['eventTimestamp'],format='mixed')
df1=df1[df1['matchResult']=='Win']
Win=df1.groupby(['eventTimestamp','platform'])['userID'].size().reset_index(name='Wins')
Win

   eventTimestamp  platform  Wins
0      2017-03-06       IOS  2671
1      2017-03-06  STEAM_PC  1815
2      2017-04-06       IOS  3078
3      2017-04-06  STEAM_PC  1894
4      2017-05-06       IOS  2884
5      2017-05-06  STEAM_PC  1437
6      2017-06-06       IOS  2383
7      2017-06-06  STEAM_PC  1279
8      2017-06-13       IOS  2057
9      2017-06-13  STEAM_PC  2159
10     2017-06-14       IOS  2161
11     2017-06-14  STEAM_PC  1735
12     2017-06-15       IOS  2300
13     2017-06-15  STEAM_PC  1675
14     2017-06-16       IOS  2222
15     2017-06-16  STEAM_PC  1898
16     2017-06-17       IOS  2623
17     2017-06-17  STEAM_PC  2110
18     2017-06-18       IOS  2359
19     2017-06-18  STEAM_PC  2230
20     2017-06-19       IOS  2154
21     2017-06-19  STEAM_PC  1447
22     2017-06-20       IOS  1929
23     2017-06-20  STEAM_PC   994
24     2017-06-21       IOS  1538
25     2017-06-21  STEAM_PC   729
26     2017-06-22       IOS  1616
27     2017-06-22  STEAM_PC   648
28     2017-06-23       IOS  1479
29     2017-06-23  STEAM_PC   607
30     2017-06-24       IOS  1418
31     2017-06-24  STEAM_PC   613
32     2017-06-25       IOS  1483
33     2017-06-25  STEAM_PC   664
34     2017-06-26       IOS  1244
35     2017-06-26  STEAM_PC   404
36     2017-06-27       IOS  1152
37     2017-06-27  STEAM_PC   392
38     2017-06-28       IOS  1432
39     2017-06-28  STEAM_PC   728
40     2017-06-29       IOS  1678
41     2017-06-29  STEAM_PC   610
42     2017-06-30       IOS  1315
43     2017-06-30  STEAM_PC   504
44     2017-07-06       IOS  2763
45     2017-07-06  STEAM_PC   955
46     2017-08-06       IOS  3098
47     2017-08-06  STEAM_PC  1000
48     2017-09-06       IOS  2459
49     2017-09-06  STEAM_PC  1156
50     2017-10-06       IOS  2829
51     2017-10-06  STEAM_PC  1171
52     2017-11-06       IOS  2941
53     2017-11-06  STEAM_PC  2175
54     2017-12-06       IOS  2346
55     2017-12-06  STEAM_PC  2735

                                      Analysis Focused:

• PayingUsers: If the player spent real money in the game or not. Count of all yes and no users

In [161]:
import pandas as pd
df4=pd.read_csv('df4.csv')
df4['PayingUsers'].replace({1:'yes',0:'no'}).value_counts()

PayingUsers
no     6292
yes    1753
Name: count, dtype: int64

• Country: Country of the players. No limitations. Maybe country analysis?

In [162]:
user_country=df4['Country'].value_counts()
user_country

Country
US    2371
GB     805
DE     788
FR     716
BR     426
      ...
BO       1
LU       1
GU       1
KH       1
GL       1
Name: count, Length: 117, dtype: int64

• Platform: Platform of the player (console / Steam.)

In [163]:
df4['Platform'].value_counts().reset_index()

   Platform  count
0       PS4   4327
1   XBOXONE   3378
2  STEAM_PC    340

• ClanJoined: If the player has joined a clan before doing a purchase

In [164]:
df4 = df4[(df4['ClanJoined'] == 1) & (df4['FirstPurchaseTheater'].isna())]
df4[['userID','ClanJoined','FirstPurchaseTheater']]

                      userID  ClanJoined  FirstPurchaseTheater
0     9ayT1EdzOUukSVW5_En5cg           1                   NaN
1     h1HD7l1yPEqvTRc1IpyhUg           1                   NaN
2     R_e6AZj3sE24y_dT8mhTPQ           1                   NaN
3     Sa6vX4ftRk68wdxCaJijZw           1                   NaN
8     UazD0_MwBEqPm0zH8QGQQw           1                   NaN
...                      ...         ...                   ...
8032  mP7BZ2XJJUWre9j6-Roa7A           1                   NaN
8035  HGcuU51hZEiJzkSFUSryCQ           1                   NaN
8036  pUNMfOPRU0a3aV1q9_BCAA           1                   NaN
8040  UOjGGKLq_EiPYgUyhDziDA           1                   NaN
8042  G1UasOg1sUiJckYq4ymecg           1                   NaN

[5161 rows x 3 columns]